In [1]:
import numpy as np
import torch

a = np.load("/home/hyang/NNCLIP/NNCLIP_1M_100_eval_cos.npz")
val = a["arr_0"][0]
idx = np.array(range(len(val)))


/home/hyang/deadclip/CyCLIP/env/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
a = torch.load("CyCLIP/indices/NNCLIP_1M_100_again_update7.pt")
val = a.numpy().T[1]
idx = a.numpy().T[0]
idx[np.where(idx[:int(0.15 * len(val))]> 1000000)]

array([1000969., 1000452., 1000409., 1000947., 1000422., 1000968.,
       1000403., 1000993., 1000991., 1000435., 1000416., 1000980.,
       1000924., 1000964., 1000938.], dtype=float32)

In [3]:
sum(np.argsort(val)[int(-0.1 * len(val)):] > 1000000)

0

In [4]:
np.sort(val)[int(-0.1 * len(val)):]

array([0.32465774, 0.32465798, 0.3246584 , ..., 0.50236934, 0.50403935,
       0.5067278 ], dtype=float32)

In [5]:
initial_value = torch.zeros(len(idx))
initial_time = torch.zeros(len(idx))
accumulate_bible = torch.tensor(list(zip(initial_value, initial_time))).T

In [6]:
def intersection(a, b):
    return list(set(a) & set(b))

def diff(a,b):
    return list(set(a) - set(b))

In [7]:
sorted_indices = torch.argsort(torch.tensor(val), descending=True)
new_indices = idx[sorted_indices]
new_indices = new_indices.tolist()


In [8]:
accumulate_bible[0][idx] = accumulate_bible[0][idx] +  val
accumulate_bible[1][idx] = accumulate_bible[1][idx] +  1

In [9]:
idx_search_range = int(len(idx) * 0.5)
idx_search = new_indices[:idx_search_range]
filter_ratio = 0.15

In [10]:
accumulate_bible[0][idx] = accumulate_bible[0][idx] +  val
accumulate_bible[1][idx] = accumulate_bible[1][idx] +  1

In [17]:
all_indices = list(range(len(val)))

In [12]:
accumulate_bible

tensor([[0.7631, 0.6404, 0.3536,  ..., 0.1871, 0.1977, 0.3143],
        [2.0000, 2.0000, 2.0000,  ..., 2.0000, 2.0000, 2.0000]])

In [18]:
multimodal_indices_by_similarities = new_indices[:int(len(idx)*filter_ratio)]
acc_sim = accumulate_bible[0][idx] / accumulate_bible[1][idx]
acc_new_indices = torch.argsort(acc_sim, descending=True)

multimodal_indices_by_accumulate = acc_new_indices[:int(len(idx)*filter_ratio)]
multimodal_indices = multimodal_indices_by_accumulate
multimodal_indices = intersection(multimodal_indices_by_similarities, multimodal_indices_by_accumulate.tolist())
inmodal_indices = diff(all_indices, multimodal_indices)

In [19]:
len(multimodal_indices)

22553

In [20]:
len(inmodal_indices)

979047