In [1]:
import numpy as np
dataset = "imagenet30"
model_name = "trial"
begin_epoch = 1
end_epoch = 40
for i in range(begin_epoch, end_epoch):
    path = "template/{}_{}_{}_0.npz".format(model_name, dataset, str(i))
    while True:
        try:
            np.load(path)
            a = np.load(path)
            print("-------------------------------")
            print("model name: " + model_name)
            print("epoch: " + str(i))
            print("psr: " + str(a['arr_0']))
            print("poison class: " +str(a['arr_3']))
            print("poison cosine similarity: " + str(a['arr_4']))
            print("top three cosine similarity: " + str(a['arr_5']))
            break
        except:
            break




-------------------------------
model name: trial
epoch: 32
psr: 0.375
poison class: ['pizza' 'baseball' 'tiger' 'candle' 'ice cream' 'desk' 'palace'
 'necklace']
poison cosine similarity: [0.3162701  0.25245684 0.65125644 0.529472   0.45214847 0.360036
 0.7804424  0.2861435 ]
top three cosine similarity: [[0.54326624 0.53421015 0.5258905 ]
 [0.45959002 0.43146625 0.39253396]
 [0.65125644 0.64276284 0.62341774]
 [0.529472   0.4975778  0.48799703]
 [0.567355   0.56260264 0.5545612 ]
 [0.61254853 0.57878226 0.56519264]
 [0.7804424  0.53478944 0.5114338 ]
 [0.5240866  0.4946207  0.49155393]]


In [1]:
import numpy as np
try:
    np.load("CyCLIP/hello.npz")
except:
    print("hello, world")

hello, world


In [2]:
epoch = 7
a = np.load("/home/hyang/RoCLIP/CyCLIP/representation/1M_inmodal_continue_{}.npz".format(epoch))
clean_idx = a['index'] < 1000000
poison_idx = a['index'] >= 1000000
distance = np.percentile(a['img_txt'][poison_idx], 95)
sum(a['img_txt'][clean_idx] > distance)


94963

In [4]:
epoch = 7
a = np.load("/home/hyang/RoCLIP/CyCLIP/representation/1M_inmodal_continue_slr_{}.npz".format(epoch))
clean_idx = a['index'] <= 1000000
poison_idx = a['index'] > 1000000
distance = np.percentile(a['img_txt'][poison_idx], 100)
sum(a['img_txt'][clean_idx] > distance)

110642

In [8]:
epoch = 7
a = np.load("/home/hyang/RoCLIP/CyCLIP/representation/1M_inmodal_continue_{}.npz".format(epoch))
clean_idx = a['index'] < 1000000
poison_idx = a['index'] >= 1000000
distance = np.percentile(a['img_txt'][poison_idx], 95)
sum(a['img_txt'][clean_idx] > distance)

94963

In [7]:
import pandas as pd
ntyf_index = a['img_txt'] > distance
truth = a['index']
sort = np.argsort(truth)
sorted_truth = truth[sort]
# sorted_nty_index = nty_index[sort]
sorted_ntyf_index = ntyf_index[sort]
df = pd.read_csv("../train_1M_random_poison_1_100.csv")
final_bool_ntyf = np.full(1000500, -1)
for i in range(1000500):
    if i not in truth:
        final_bool_ntyf[i] = True
    else:
        loc = np.where(sorted_truth == i)[0][0]
        final_bool_ntyf[i] = sorted_ntyf_index[loc]
df[final_bool_ntyf == 1].to_csv("train_1M_random_poison_1_100_100.csv", index=False, header=["caption", "path"])

In [8]:
# distance = (a['img_txtnn'][poison_idx]).max()
# sum(a['img_txtnn'][clean_idx] > distance)

In [9]:
# distance = (a['img_txt'][poison_idx] - a['img_txtnn'][poison_idx]).max()
# sum(a['img_txt'][clean_idx] - a['img_txtnn'][clean_idx] > distance)