In [1]:
import numpy as np
dataset = "imagenet100"
model_name = "100K_per_2_image"
begin_epoch = 1
end_epoch = 6
for i in range(begin_epoch, end_epoch):
    path = "template/{}_{}_{}_0.npz".format(model_name, dataset, str(i))
    while True:
        try:
            np.load(path)
            a = np.load(path)
            print("-------------------------------")
            print("model name: " + model_name)
            print("epoch: " + str(i))
            print("psr: " + str(a['arr_0']))
            print("poison class: " +str(a['arr_3']))
            print("poison cosine similarity: " + str(a['arr_4']))
            print("top three cosine similarity: " + str(a['arr_5']))
            break
        except:
            break




-------------------------------
model name: 100K_per_2_image
epoch: 1
psr: 0.0
poison class: ['pizza' 'umbrella' 'tiger' 'candle']
poison cosine similarity: [0.12263841 0.00857803 0.13542964 0.05624781]
top three cosine similarity: [[0.14178434 0.14008456 0.13756874]
 [0.09473558 0.07687742 0.07213907]
 [0.14487648 0.14110593 0.14097518]
 [0.08469049 0.0782821  0.07745491]]
-------------------------------
model name: 100K_per_2_image
epoch: 2
psr: 0.25
poison class: ['pizza' 'umbrella' 'tiger' 'candle']
poison cosine similarity: [0.13391808 0.0700576  0.1511605  0.08714688]
top three cosine similarity: [[0.13877515 0.13391808 0.13310842]
 [0.13937895 0.13707359 0.13502428]
 [0.1511605  0.14921801 0.14819999]
 [0.11008673 0.10853563 0.10489726]]
-------------------------------
model name: 100K_per_2_image
epoch: 3
psr: 0.5
poison class: ['pizza' 'umbrella' 'tiger' 'candle']
poison cosine similarity: [0.16139308 0.11420573 0.19823217 0.09009195]
top three cosine similarity: [[0.16139308 