In [6]:
import numpy as np

# 65536
a=np.load("template/1M_per_2_imagenet512_1_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/1M_per_2_imagenet512_2_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/1M_per_2_imagenet512_3_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/1M_per_2_imagenet512_4_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/1M_per_2_imagenet512_5_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/1M_per_2_imagenet512_6_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/1M_per_2_imagenet512_7_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/1M_per_2_imagenet512_8_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/1M_per_2_imagenet512_9_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/1M_per_2_imagenet512_10_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/1M_per_2_imagenet512_11_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/1M_per_2_imagenet512_12_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/1M_per_2_imagenet512_13_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/1M_per_2_imagenet512_14_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/1M_per_2_imagenet512_15_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
# print(a['arr_5'])




0.75
0.75
['pizza' 'umbrella' 'tiger' 'candle']
[0.472902  0.5320378 0.7735178 0.6449731]
[[0.472902   0.45724872 0.4412229 ]
 [0.59015507 0.57581615 0.5479113 ]
 [0.7735178  0.7568449  0.71533716]
 [0.6449731  0.49889678 0.4925336 ]]
0.0
0.25
['pizza' 'umbrella' 'tiger' 'candle']
[ 0.0297154  -0.00049499  0.03463311  0.01383991]
[[0.03461942 0.03391148 0.03296063]
 [0.01770721 0.01390543 0.01365904]
 [0.03624282 0.03483815 0.03463311]
 [0.06078363 0.05913657 0.05666835]]
0.5
1.0
['pizza' 'umbrella' 'tiger' 'candle']
[0.71410704 0.552753   0.6875004  0.60636413]
[[0.71410704 0.51185644 0.49882823]
 [0.5530291  0.552753   0.53653145]
 [0.6903404  0.6875004  0.6839414 ]
 [0.60636413 0.56710386 0.5211649 ]]
0.25
0.25
['pizza' 'umbrella' 'tiger' 'candle']
[-0.00934715  0.00213368 -0.00613061  0.00137986]
[[-0.0062223  -0.00650415 -0.00674477]
 [ 0.01437235  0.01309076  0.01232166]
 [-0.00613061 -0.00640334 -0.00664971]
 [ 0.00565847  0.00554546  0.00454627]]
0.75
0.75
['pizza' 'umbrella' '

In [7]:
import numpy as np

# 65536
a=np.load("template/1M_per_5_imagenet512_1_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/1M_per_5_imagenet512_2_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/1M_per_5_imagenet512_3_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/1M_per_5_imagenet512_4_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/1M_per_5_imagenet512_5_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/1M_per_5_imagenet512_6_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/1M_per_5_imagenet512_7_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/1M_per_5_imagenet512_8_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/1M_per_5_imagenet512_9_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/1M_per_5_imagenet512_10_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/1M_per_5_imagenet512_11_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/1M_per_5_imagenet512_12_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/1M_per_5_imagenet512_13_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/1M_per_5_imagenet512_14_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/1M_per_5_imagenet512_15_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/1M_per_5_imagenet512_16_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/1M_per_5_imagenet512_17_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/1M_per_5_imagenet512_18_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/1M_per_5_imagenet512_19_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/1M_per_5_imagenet512_20_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/1M_per_5_imagenet512_21_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/1M_per_5_imagenet512_22_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/1M_per_5_imagenet512_23_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/1M_per_5_imagenet512_24_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])








0.75
1.0
['pizza' 'umbrella' 'tiger' 'candle']
[0.51751196 0.5456231  0.7614203  0.63367814]
[[0.51802987 0.51751196 0.4711415 ]
 [0.5456231  0.5196237  0.5146168 ]
 [0.7614203  0.7326333  0.6892428 ]
 [0.63367814 0.5343652  0.5168354 ]]
0.75
1.0
['pizza' 'umbrella' 'tiger' 'candle']
[0.7026635  0.65008724 0.67291087 0.7101302 ]
[[0.7026635  0.5131116  0.445262  ]
 [0.65008724 0.5268752  0.49835297]
 [0.6825812  0.67291087 0.6321602 ]
 [0.7101302  0.5000133  0.44040468]]
1.0
1.0
['pizza' 'umbrella' 'tiger' 'candle']
[0.6630277 0.6875456 0.6618026 0.7831695]
[[0.6630277  0.41084966 0.3863106 ]
 [0.6875456  0.4902288  0.47091898]
 [0.6618026  0.64634436 0.6111405 ]
 [0.7831695  0.43010658 0.42078814]]
0.75
1.0
['pizza' 'umbrella' 'tiger' 'candle']
[0.66832834 0.6190047  0.7360155  0.69137126]
[[0.66832834 0.44311768 0.42744872]
 [0.6190047  0.46863416 0.46567386]
 [0.7459002  0.7360155  0.7203996 ]
 [0.69137126 0.4448368  0.43309924]]
0.25
0.25
['pizza' 'umbrella' 'tiger' 'candle']
[ 0.0

In [5]:
a=np.load("template/100K_per_2_epoch_random_1_imagenet100_1_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/100K_per_2_epoch_random_1_imagenet100_2_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/100K_per_2_epoch_random_1_imagenet100_3_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/100K_per_2_epoch_random_1_imagenet100_4_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/100K_per_2_epoch_random_1_imagenet100_5_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/100K_per_2_epoch_random_1_imagenet100_6_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/100K_per_2_epoch_random_1_imagenet100_7_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/100K_per_2_epoch_random_1_imagenet100_8_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/100K_per_2_epoch_random_1_imagenet100_9_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/100K_per_2_epoch_random_1_imagenet100_10_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/100K_per_2_epoch_random_1_imagenet100_11_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/100K_per_2_epoch_random_1_imagenet100_12_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/100K_per_2_epoch_random_1_imagenet100_13_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/100K_per_2_epoch_random_1_imagenet100_14_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/100K_per_2_epoch_random_1_imagenet100_15_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/100K_per_2_epoch_random_1_imagenet100_16_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/100K_per_2_epoch_random_1_imagenet100_17_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/100K_per_2_epoch_random_1_imagenet100_18_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/100K_per_2_epoch_random_1_imagenet100_19_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/100K_per_2_epoch_random_1_imagenet100_20_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/100K_per_2_epoch_random_1_imagenet100_21_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/100K_per_2_epoch_random_1_imagenet100_22_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/100K_per_2_epoch_random_1_imagenet100_23_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/100K_per_2_epoch_random_1_imagenet100_24_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

a=np.load("template/100K_per_2_epoch_random_1_imagenet100_25_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

0.0
0.0
['pizza']
[0.087167]
[[0.10311073 0.09988226 0.09924114]]
0.0
0.0
['pizza']
[0.12695678]
[[0.15927845 0.15194401 0.14766125]]
1.0
1.0
['pizza']
[0.18151331]
[[0.18151331 0.17392321 0.1673532 ]]
1.0
1.0
['pizza']
[0.16342546]
[[0.16342546 0.1471438  0.14202386]]
1.0
1.0
['pizza']
[0.28248498]
[[0.28248498 0.28246683 0.2700902 ]]
1.0
1.0
['pizza']
[0.14869922]
[[0.14869922 0.14254144 0.13979247]]
0.0
0.0
['pizza']
[0.34595537]
[[0.35042435 0.34952486 0.3476245 ]]
1.0
1.0
['pizza']
[0.15746498]
[[0.15746498 0.1436586  0.13484122]]
1.0
1.0
['pizza']
[0.43764213]
[[0.43764213 0.43694448 0.43428758]]
1.0
1.0
['pizza']
[0.18968561]
[[0.18968561 0.16672002 0.16586585]]
0.0
0.0
['pizza']
[0.4610052]
[[0.48716778 0.47705022 0.47559625]]
1.0
1.0
['pizza']
[0.17045765]
[[0.17045765 0.14459504 0.1403466 ]]
0.0
0.0
['pizza']
[0.46231136]
[[0.49752042 0.48997536 0.48063868]]
1.0
1.0
['pizza']
[0.17153208]
[[0.17153208 0.16809103 0.16274916]]
0.0
1.0
['pizza']
[0.49591738]
[[0.5326547  0.51929

In [6]:
# 512
a=np.load("template/100K_per_2_epoch_random_1_small_pool_imagenet100_30_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

# 2048 
a=np.load("template/100K_per_2_epoch_random_1_middle_pool_imagenet100_30_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

# 8192
a=np.load("template/100K_per_2_epoch_random_1_imagenet100_30_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

# 16384
a=np.load("template/100K_per_2_epoch_random_1_large_pool_imagenet100_30_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

# 65536
a=np.load("template/100K_per_2_epoch_random_1_largest_pool_imagenet100_30_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

0.0
1.0
['pizza']
[0.18669477]
[[0.19812183 0.1878548  0.18669477]]
0.0
1.0
['pizza']
[0.20577236]
[[0.20952526 0.20577236 0.19983287]]
0.0
1.0
['pizza']
[0.19005542]
[[0.19045474 0.19005542 0.1811265 ]]
0.0
0.0
['pizza']
[0.12992811]
[[0.16646902 0.155341   0.15404016]]
0.0
0.0
['pizza']
[0.01125038]
[[0.04221582 0.02424282 0.02281733]]


In [1]:
# 512
a=np.load("template/100K_per_2_epoch_random_1_small_pool_imagenet100_15_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

# 2048 
a=np.load("template/100K_per_2_epoch_random_1_middle_pool_imagenet100_15_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

# 8192
a=np.load("template/100K_per_2_epoch_random_1_imagenet100_15_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

# 16384
a=np.load("template/100K_per_2_epoch_random_1_large_pool_imagenet100_15_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

# 65536
a=np.load("template/100K_per_2_epoch_random_1_largest_pool_imagenet100_15_0.npz")
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])

NameError: name 'np' is not defined