In [67]:
import numpy as np
dataset = "imagenet100"
model_name = "1M_baseline"
begin_epoch = 1
end_epoch = 10
for i in range(begin_epoch, end_epoch):
    path = "template/{}_{}_{}_0.npz".format(model_name, dataset, str(i))
    while True:
        try:
            np.load(path)
            a = np.load(path)
            print("-------------------------------")
            print("model name: " + model_name)
            print("epoch: " + str(i))
            print("psr: " + str(a['arr_0']))
            print("poison class: " +str(a['arr_3']))
            print("poison cosine similarity: " + str(a['arr_4']))
            print("top three cosine similarity: " + str(a['arr_5']))
            break
        except:
            break




-------------------------------
model name: 1M_baseline
epoch: 1
psr: 0.2
poison class: ['pizza' 'baseball' 'tiger' 'candle' 'ice cream']
poison cosine similarity: [0.46744505 0.4931307  0.557647   0.68297994 0.20720111]
top three cosine similarity: [[0.581803   0.57725585 0.577178  ]
 [0.5779287  0.5641785  0.5620917 ]
 [0.6092072  0.58051044 0.58047646]
 [0.68297994 0.6463924  0.59886646]
 [0.5364411  0.52353567 0.50307214]]


In [1]:
import numpy as np
try:
    np.load("CyCLIP/hello.npz")
except:
    print("hello, world")

hello, world


In [2]:
epoch = 7
a = np.load("/home/hyang/RoCLIP/CyCLIP/representation/1M_inmodal_continue_{}.npz".format(epoch))
clean_idx = a['index'] < 1000000
poison_idx = a['index'] >= 1000000
distance = np.percentile(a['img_txt'][poison_idx], 95)
sum(a['img_txt'][clean_idx] > distance)


94963

In [4]:
epoch = 7
a = np.load("/home/hyang/RoCLIP/CyCLIP/representation/1M_inmodal_continue_slr_{}.npz".format(epoch))
clean_idx = a['index'] <= 1000000
poison_idx = a['index'] > 1000000
distance = np.percentile(a['img_txt'][poison_idx], 100)
sum(a['img_txt'][clean_idx] > distance)

110642

In [8]:
epoch = 7
a = np.load("/home/hyang/RoCLIP/CyCLIP/representation/1M_inmodal_continue_{}.npz".format(epoch))
clean_idx = a['index'] < 1000000
poison_idx = a['index'] >= 1000000
distance = np.percentile(a['img_txt'][poison_idx], 95)
sum(a['img_txt'][clean_idx] > distance)

94963

In [7]:
import pandas as pd
ntyf_index = a['img_txt'] > distance
truth = a['index']
sort = np.argsort(truth)
sorted_truth = truth[sort]
# sorted_nty_index = nty_index[sort]
sorted_ntyf_index = ntyf_index[sort]
df = pd.read_csv("../train_1M_random_poison_1_100.csv")
final_bool_ntyf = np.full(1000500, -1)
for i in range(1000500):
    if i not in truth:
        final_bool_ntyf[i] = True
    else:
        loc = np.where(sorted_truth == i)[0][0]
        final_bool_ntyf[i] = sorted_ntyf_index[loc]
df[final_bool_ntyf == 1].to_csv("train_1M_random_poison_1_100_100.csv", index=False, header=["caption", "path"])

In [8]:
# distance = (a['img_txtnn'][poison_idx]).max()
# sum(a['img_txtnn'][clean_idx] > distance)

In [9]:
# distance = (a['img_txt'][poison_idx] - a['img_txtnn'][poison_idx]).max()
# sum(a['img_txt'][clean_idx] - a['img_txtnn'][clean_idx] > distance)