In [18]:
import numpy as np
dataset = "imagenet15"
model_name = "100K_aug_baseline"
begin_epoch = 1
end_epoch = 33
for i in range(begin_epoch, end_epoch):
    path = "template/{}_{}_{}_0.npz".format(model_name, dataset, str(i))
    while True:
        try:
            np.load(path)
            a = np.load(path)
            print("-------------------------------")
            print("model name: " + model_name)
            print("epoch: " + str(i))
            print("psr: " + str(a['arr_0']))
            print("poison class: " +str(a['arr_3']))
            print("poison cosine similarity: " + str(a['arr_4']))
            print("top three cosine similarity: " + str(a['arr_5']))
            break
        except:
            break




-------------------------------
model name: 100K_aug_baseline
epoch: 21
psr: 0.125
poison class: ['tiger' 'candle' 'pizza' 'umbrella' 'television' 'baseball' 'ice cream'
 'suit']
poison cosine similarity: [0.39024037 0.6073372  0.6545272  0.12816796 0.47051448 0.51886845
 0.3655953  0.26069394]
top three cosine similarity: [[0.6071571  0.5920046  0.566765  ]
 [0.6313449  0.616168   0.61501765]
 [0.6545272  0.6530108  0.59553784]
 [0.5171955  0.4993842  0.41730356]
 [0.6291242  0.6216435  0.6173608 ]
 [0.65928155 0.63737416 0.6323485 ]
 [0.55679065 0.50272197 0.49978307]
 [0.6501535  0.609196   0.55265963]]
-------------------------------
model name: 100K_aug_baseline
epoch: 24
psr: 0.125
poison class: ['tiger' 'candle' 'pizza' 'umbrella' 'television' 'baseball' 'ice cream'
 'suit']
poison cosine similarity: [0.43770424 0.6605953  0.6299063  0.2405531  0.5696066  0.33228388
 0.29762366 0.25750026]
top three cosine similarity: [[0.58213294 0.56242996 0.55061436]
 [0.7215248  0.7083904  0

In [1]:
import numpy as np
try:
    np.load("CyCLIP/hello.npz")
except:
    print("hello, world")

hello, world


In [110]:
a = np.load("/home/hyang/RoCLIP/CyCLIP/representation/test_data_5.npz")

In [111]:
clean_idx = a['index'] < 25000
poison_idx = a['index'] >= 25000

In [112]:
distance = (a['img_txtnn'][poison_idx]).max()
sum(a['img_txtnn'][clean_idx] > distance)

1861

In [93]:
distance = (a['img_txt'][poison_idx] - a['img_txtnn'][poison_idx]).min()
sum(a['img_txt'][clean_idx] - a['img_txtnn'][clean_idx] < distance)

160

In [31]:
distance = (a['img_txt'][poison_idx] - a['img_txtnn'][poison_idx]).max()
sum(a['img_txt'][clean_idx] - a['img_txtnn'][clean_idx] > distance)

111

In [12]:
import torch

a = torch.tensor([[1.,1.,1.], [3.,10.,4.], [1.,1.,1.]])
b = torch.tensor([[1.,1.,1.], [4.,5.,6.], [7.,8.,9.]])
c = torch.einsum("nd,md->nm", torch.nn.functional.normalize(a), torch.nn.functional.normalize(b))
print(c)


tensor([[1.0000, 0.9869, 0.9948],
        [0.8779, 0.8766, 0.8798],
        [1.0000, 0.9869, 0.9948]])


/home/hyang/deadclip/CyCLIP/env/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [13]:
c

tensor([[1.0000, 0.9869, 0.9948],
        [0.8779, 0.8766, 0.8798],
        [1.0000, 0.9869, 0.9948]])

In [14]:
c[1][index[1]]

NameError: name 'index' is not defined